//HintName: HeaderControl.generated.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace Maui.BindableProperty.Generator.Demo.CustomControls
{
    public partial class HeaderControl
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Maui.BindableProperty.Generator.Core.BindableProperty.AutoBindablePropertyGenerator", "0.10.0.0")]
        public static readonly Microsoft.Maui.Controls.BindableProperty ZipCodeProperty =
                                        Microsoft.Maui.Controls.BindableProperty.Create(
                                                                nameof(ZipCode),
                                                                typeof(string),
                                                                typeof(HeaderControl),
                                                                defaultValue: default(string?),
                                                                validateValue: ValidateNotNull);

        [global::System.CodeDom.Compiler.GeneratedCode("Maui.BindableProperty.Generator.Core.BindableProperty.AutoBindablePropertyGenerator", "0.10.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? ZipCode
        {
            get => (string?)GetValue(ZipCodeProperty);
            set => SetValue(ZipCodeProperty, value);
        }
    }
}
