//HintName: HeaderControl.generated.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace Maui.BindableProperty.Generator.Demo.CustomControls
{
    public partial class HeaderControl
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Maui.BindableProperty.Generator.Core.BindableProperty.AutoBindablePropertyGenerator", "0.10.0.0")]
        public static readonly Microsoft.Maui.Controls.BindableProperty LastNameProperty =
                                        Microsoft.Maui.Controls.BindableProperty.Create(
                                                                nameof(LastName),
                                                                typeof(string),
                                                                typeof(HeaderControl),
                                                                defaultValue: default(string?));

        [global::System.CodeDom.Compiler.GeneratedCode("Maui.BindableProperty.Generator.Core.BindableProperty.AutoBindablePropertyGenerator", "0.10.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? LastName
        {
            get => (string?)GetValue(LastNameProperty);
            set => SetValue(LastNameProperty, value);
        }
    }
}
